<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="dijesh-PC" name="week3_homework.CreateContacts" tests="3" failures="0" timestamp="3 Dec 2017 07:29:25 GMT" time="236.227" errors="1">
  <testcase name="createContacts" time="84.074" classname="week3_homework.CreateContacts"/>
  <testcase name="createContacts" time="94.684" classname="week3_homework.CreateContacts"/>
  <testcase name="createContacts" time="57.469" classname="week3_homework.CreateContacts">
    <error type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
	at methods.SeMethods_1.locateElement(SeMethods_1.java:101)
	at week3_homework.CreateContacts.createContacts(CreateContacts.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
]]>
    </error>
  </testcase> <!-- createContacts -->
</testsuite> <!-- week3_homework.CreateContacts -->
